"""Temporary script to regenerate all 4 Petro Smetaniuk payrolls with corrected YTD."""
from generate_payroll import generate_payroll, PAYROLL_DATA

base = dict(PAYROLL_DATA)  # copy branding assets etc.

payrolls = [
    {
        **base,
        "employee_name":  "Petro Smetaniuk",
        "employee_id":    "N/A",
        "employee_address": ["305, 3431-139 Ave", "Edmonton, AB", "T5Y 1Z4"],
        "position":       "Graphic Designer",
        "payment_method": "Cheque",
        "period_from":    "December 12th, 2025",
        "period_to":      "December 27th, 2025",
        "payment_date":   "January 1st, 2026",
        "regular_rate":   23.25,
        "regular_hours":  60.25,
        "other_rate":     None,
        "other_hours":    None,
        "cpp":            74.67,
        "ei":             22.97,
        "fed_tax":        85.00,
        "prov_tax":       37.45,
        "ytd_gross":      None,        # first period — auto
        "ytd_net":        None,
    },
    {
        **base,
        "employee_name":  "Petro Smetaniuk",
        "employee_id":    "N/A",
        "employee_address": ["305, 3431-139 Ave", "Edmonton, AB", "T5Y 1Z4"],
        "position":       "Graphic Designer",
        "payment_method": "Cheque",
        "period_from":    "December 28th, 2025",
        "period_to":      "January 11th, 2026",
        "payment_date":   "January 15th, 2026",
        "regular_rate":   23.25,
        "regular_hours":  72,
        "other_rate":     None,
        "other_hours":    None,
        "cpp":            90.93,
        "ei":             27.29,
        "fed_tax":        114.15,
        "prov_tax":       48.25,
        "ytd_gross":      3074.81,
        "ytd_net":        2574.10,
    },
    {
        **base,
        "employee_name":  "Petro Smetaniuk",
        "employee_id":    "N/A",
        "employee_address": ["305, 3431-139 Ave", "Edmonton, AB", "T5Y 1Z4"],
        "position":       "Graphic Designer",
        "payment_method": "E-Transfer",
        "period_from":    "January 12th, 2026",
        "period_to":      "January 27th, 2026",
        "payment_date":   "February 1st, 2026",
        "regular_rate":   23.25,
        "regular_hours":  106.25,
        "other_rate":     None,
        "other_hours":    None,
        "cpp":            138.31,
        "ei":             40.27,
        "fed_tax":        214.85,
        "prov_tax":       107.80,
        "ytd_gross":      5545.12,
        "ytd_net":        4543.18,
    },
    {
        **base,
        "employee_name":  "Petro Smetaniuk",
        "employee_id":    "N/A",
        "employee_address": ["305, 3431-139 Ave", "Edmonton, AB", "T5Y 1Z4"],
        "position":       "Graphic Designer",
        "payment_method": "E-Transfer",
        "period_from":    "January 28th, 2026",
        "period_to":      "February 11th, 2026",
        "payment_date":   "February 15th, 2026",
        "regular_rate":   23.25,
        "regular_hours":  98.5,
        "other_rate":     None,
        "other_hours":    None,
        "cpp":            127.59,
        "ei":             37.33,
        "fed_tax":        193.35,
        "prov_tax":       94.50,
        "ytd_gross":      7835.25,
        "ytd_net":        6380.54,
    },
]

for p in payrolls:
    generate_payroll(p)

print("\nAll 4 payrolls regenerated with corrected YTD!")
